from enum import Enum


class SlotName(Enum):
    PRESSAO_ARTERIAL_SISTOLICA = "slot_pressao_arterial_sistolica"
    NIVEL_DE_CONSCIENCIA = "slot_nivel_de_consciencia"
    FREQUENCIA_RESPIRATORIA = "slot_frequencia_respiratoria"
    UREIA = "slot_ureia"
    PRESSAO_ARTERIAL_DIASTOLICA = "slot_pressao_arterial_diastolica"
    IDADE = "slot_idade"
    SATURACAO_DE_OXIGENIO = "slot_saturacao_de_oxigenio"
    COMORBIDADE_DPOC = "slot_comorbidade_dpoc"
    COMORBIDADE_CIRROSE = "slot_comorbidade_cirrose"
    COMORBIDADE_IRC = "slot_comorbidade_irc"
    COMORBIDADE_CANCER = "slot_comorbidade_cancer"
    COMORBIDADE_DIABETES = "slot_comorbidade_diabetes"
    COMORBIDADE_IC = "slot_comorbidade_ic"
    COMORBIDADE_ALCOOLISMO = "slot_comorbidade_alcoolismo"
    COMORBIDADE_ASPLENIA = "slot_comorbidade_asplenia"
    COMORBIDADE_IMUNOSSUPRESSAO = "slot_comorbidade_imunossupressao"
    USO_ATB_3_MESES = "slot_uso_atb_3_meses"
    LOCAL_TRATAMENTO = "slot_local_tratamento"
    CURB65 = "slot_curb65"
    DEFAULT = "default"


class EntityName(Enum):
    PRESSAO_ARTERIAL_SISTOLICA = "entity_pressao_arterial_sistolica"
    NIVEL_DE_CONSCIENCIA = "entity_nivel_de_consciencia"
    FREQUENCIA_RESPIRATORIA = "entity_frequencia_respiratoria"
    UREIA = "entity_ureia"
    PRESSAO_ARTERIAL_DIASTOLICA = "entity_pressao_arterial_diastolica"
    IDADE = "entity_idade"
    SATURACAO_DE_OXIGENIO = "entity_saturacao_de_oxigenio"
    COMORBIDADE_DPOC = "entity_comorbidade_dpoc"
    COMORBIDADE_CIRROSE = "entity_comorbidade_cirrose"
    COMORBIDADE_IRC = "entity_comorbidade_irc"
    COMORBIDADE_CANCER = "entity_comorbidade_cancer"
    COMORBIDADE_DIABETES = "entity_comorbidade_diabetes"
    COMORBIDADE_IC = "entity_comorbidade_ic"
    COMORBIDADE_ALCOOLISMO = "entity_comorbidade_alcoolismo"
    COMORBIDADE_ASPLENIA = "entity_comorbidade_asplenia"
    COMORBIDADE_IMUNOSSUPRESSAO = "entity_comorbidade_imunossupressao"
    USO_ATB_3_MESES = "entity_uso_atb_3_meses"
    LOCAL_TRATAMENTO = "entity_local_tratamento"
    CURB65 = "entity_curb65"
