# -- number of replicas to deploy
replicaCount: 1
image:
  # -- registry where the HAPI FHIR server image is hosted
  registry: docker.io
  # -- the path inside the repository
  repository: laurabot/laura-care-duvidas-generalista-actions
  # -- the image tag. As of v5.7.0, this is the `distroless` flavor by default, add `-tomcat` to use the Tomcat-based image.
  tag: ""
  # tag: "v6.2.1@sha256:8d1b4c1c8abd613f685267a3dda494d87aba4cff449eed39902a6ece2c086f3c"
  # -- image pullPolicy to use
  pullPolicy: IfNotPresent
# -- image pull secrets to use when pulling the image
imagePullSecrets: []
# -- override the chart name
nameOverride: ""
# -- override the chart fullname
fullnameOverride: ""
# -- annotations applied to the server deployment
deploymentAnnotations: {}
# -- annotations applied to the server pod
podAnnotations: {}
# -- pod security context
podSecurityContext: {}
# fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001
# service to expose the server
service:
  # -- service type
  type: ClusterIP
  # -- port where the server will be exposed at
  port: 80
  internalPort: 5055
ingress:
  # -- whether to create an Ingress to expose the FHIR server HTTP endpoint
  enabled: false
  # -- provide any additional annotations which may be required. Evaluated as a template.
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host:  chart-example.local
      pathType: ImplementationSpecific
      paths: ["/"]
  # -- ingress TLS config
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

# -- node selector for the pod
nodeSelector: {}
# -- pod tolerations
tolerations: []
# -- pod affinity
affinity: {}
# -- pod topology spread configuration
# see: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#api
topologySpreadConstraints: []
# - maxSkew: 1
#   topologyKey: topology.kubernetes.io/zone
#   whenUnsatisfiable: ScheduleAnyway
#   labelSelector:
#     matchLabels:
#       app.kubernetes.io/instance: hapi-fhir-jpaserver
#       app.kubernetes.io/name: hapi-fhir-jpaserver

readinessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 20
  path: "/health"
startupProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 30
  path: "/health"
livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 30
  path: "/health"

# -- extra environment variables to set on the server container
extraEnv: []
# - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
#   value: "true"

podDisruptionBudget:
  # -- Enable PodDisruptionBudget for the server pods.
  # uses policy/v1/PodDisruptionBudget thus requiring k8s 1.21+
  enabled: false
  # -- minimum available instances
  minAvailable: 1
  # -- maximum unavailable instances
  maxUnavailable: ""

env:
  NAME_BOT: ""

secrets:
  chatbots-common-secrets:
    - name: AMPLITUDE_API_KEY
      alias: AMPLITUDE_API_KEY
  
  laura-graphql-secrets:
    - name: URL_LAURA_GRAPHQL
      alias: GRAPHQL_URL
    - name: JWT_SECRET_LAURA_GRAPHQL
      alias: GRAPHQL_SECRET
  
  rabbitmq-secrets:
    - name: RABBITMQ_CONVERSATION_DOUBTS_CONFIG
      alias: RABBITMQ_CONFIG
    - name: RABBITMQ_RASA_DOUBTS_EXCHANGE
      alias: RABBITMQ_EXCHANGE
    - name: RABBITMQ_PA_RESOURCES_HOST
      alias: RABBITMQ_HOST
    - name: RABBITMQ_GUEST_PASSWORD
      alias: RABBITMQ_PASSWORD
    - name: RABBITMQ_GUEST_USERNAME
      alias: RABBITMQ_USERNAME
